
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.FileChooserWidget filechooserwidget1;

	private global::Gtk.Table table1;

	private global::Gtk.Entry commentEntry;

	private global::Gtk.Label commentLabel;

	private global::Gtk.Entry createdByEntry;

	private global::Gtk.Label createdByLabel;

	private global::Gtk.Entry creationDateEntry;

	private global::Gtk.Label creationDateLabel;

	private global::Gtk.Entry pieceLengthEntry;

	private global::Gtk.Label pieceLengthLabel;

	private global::Gtk.Entry trackerEntry;

	private global::Gtk.Label trackerMainLabel;

	private global::Gtk.Label trackersBackupLabel;

	private global::Gtk.Entry trackersEntry;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TreeView filesListView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("BitTorrent Client");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.filechooserwidget1 = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
		this.filechooserwidget1.Name = "filechooserwidget1";
		this.vbox1.Add(this.filechooserwidget1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.filechooserwidget1]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.commentEntry = new global::Gtk.Entry();
		this.commentEntry.CanFocus = true;
		this.commentEntry.Name = "commentEntry";
		this.commentEntry.IsEditable = true;
		this.commentEntry.InvisibleChar = '•';
		this.table1.Add(this.commentEntry);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.commentEntry]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.commentLabel = new global::Gtk.Label();
		this.commentLabel.Name = "commentLabel";
		this.commentLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Comment:");
		this.table1.Add(this.commentLabel);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.commentLabel]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.createdByEntry = new global::Gtk.Entry();
		this.createdByEntry.CanFocus = true;
		this.createdByEntry.Name = "createdByEntry";
		this.createdByEntry.IsEditable = true;
		this.createdByEntry.InvisibleChar = '•';
		this.table1.Add(this.createdByEntry);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.createdByEntry]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.createdByLabel = new global::Gtk.Label();
		this.createdByLabel.Name = "createdByLabel";
		this.createdByLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Created By:");
		this.table1.Add(this.createdByLabel);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.createdByLabel]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.creationDateEntry = new global::Gtk.Entry();
		this.creationDateEntry.CanFocus = true;
		this.creationDateEntry.Name = "creationDateEntry";
		this.creationDateEntry.IsEditable = true;
		this.creationDateEntry.InvisibleChar = '•';
		this.table1.Add(this.creationDateEntry);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.creationDateEntry]));
		w6.TopAttach = ((uint)(4));
		w6.BottomAttach = ((uint)(5));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.creationDateLabel = new global::Gtk.Label();
		this.creationDateLabel.Name = "creationDateLabel";
		this.creationDateLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Creation Date:");
		this.table1.Add(this.creationDateLabel);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.creationDateLabel]));
		w7.TopAttach = ((uint)(4));
		w7.BottomAttach = ((uint)(5));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.pieceLengthEntry = new global::Gtk.Entry();
		this.pieceLengthEntry.CanFocus = true;
		this.pieceLengthEntry.Name = "pieceLengthEntry";
		this.pieceLengthEntry.IsEditable = true;
		this.pieceLengthEntry.InvisibleChar = '•';
		this.table1.Add(this.pieceLengthEntry);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.pieceLengthEntry]));
		w8.TopAttach = ((uint)(5));
		w8.BottomAttach = ((uint)(6));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.pieceLengthLabel = new global::Gtk.Label();
		this.pieceLengthLabel.Name = "pieceLengthLabel";
		this.pieceLengthLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Piece Length:");
		this.table1.Add(this.pieceLengthLabel);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.pieceLengthLabel]));
		w9.TopAttach = ((uint)(5));
		w9.BottomAttach = ((uint)(6));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.trackerEntry = new global::Gtk.Entry();
		this.trackerEntry.CanFocus = true;
		this.trackerEntry.Name = "trackerEntry";
		this.trackerEntry.IsEditable = true;
		this.trackerEntry.InvisibleChar = '•';
		this.table1.Add(this.trackerEntry);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.trackerEntry]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.trackerMainLabel = new global::Gtk.Label();
		this.trackerMainLabel.Name = "trackerMainLabel";
		this.trackerMainLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Tracker (main):");
		this.table1.Add(this.trackerMainLabel);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.trackerMainLabel]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.trackersBackupLabel = new global::Gtk.Label();
		this.trackersBackupLabel.Name = "trackersBackupLabel";
		this.trackersBackupLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Trackers (backup):");
		this.table1.Add(this.trackersBackupLabel);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.trackersBackupLabel]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.trackersEntry = new global::Gtk.Entry();
		this.trackersEntry.CanFocus = true;
		this.trackersEntry.Name = "trackersEntry";
		this.trackersEntry.IsEditable = true;
		this.trackersEntry.InvisibleChar = '•';
		this.table1.Add(this.trackersEntry);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.trackersEntry]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.filesListView = new global::Gtk.TreeView();
		this.filesListView.CanFocus = true;
		this.filesListView.Name = "filesListView";
		this.filesListView.EnableSearch = false;
		this.GtkScrolledWindow2.Add(this.filesListView);
		this.vbox1.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow2]));
		w16.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1089;
		this.DefaultHeight = 537;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.filechooserwidget1.FileActivated += new global::System.EventHandler(this.OnFilechooserwidget1FileActivated);
	}
}
