
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox contactsDBLayout;

	private global::Gtk.ScrolledWindow contactsDBScrollWindow;

	private global::Gtk.TreeView contactsDBTreeView;

	private global::Gtk.HButtonBox processButtons;

	private global::Gtk.Button createButton;

	private global::Gtk.Button readButton;

	private global::Gtk.Button updateButton;

	private global::Gtk.Button deleteButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Contacts DB Application");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.contactsDBLayout = new global::Gtk.VBox();
		this.contactsDBLayout.CanDefault = true;
		this.contactsDBLayout.Name = "contactsDBLayout";
		this.contactsDBLayout.Spacing = 6;
		this.contactsDBLayout.BorderWidth = ((uint)(5));
		// Container child contactsDBLayout.Gtk.Box+BoxChild
		this.contactsDBScrollWindow = new global::Gtk.ScrolledWindow();
		this.contactsDBScrollWindow.CanFocus = true;
		this.contactsDBScrollWindow.Name = "contactsDBScrollWindow";
		this.contactsDBScrollWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child contactsDBScrollWindow.Gtk.Container+ContainerChild
		this.contactsDBTreeView = new global::Gtk.TreeView();
		this.contactsDBTreeView.CanFocus = true;
		this.contactsDBTreeView.Name = "contactsDBTreeView";
		this.contactsDBScrollWindow.Add(this.contactsDBTreeView);
		this.contactsDBLayout.Add(this.contactsDBScrollWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.contactsDBLayout[this.contactsDBScrollWindow]));
		w2.Position = 0;
		// Container child contactsDBLayout.Gtk.Box+BoxChild
		this.processButtons = new global::Gtk.HButtonBox();
		this.processButtons.Name = "processButtons";
		this.processButtons.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child processButtons.Gtk.ButtonBox+ButtonBoxChild
		this.createButton = new global::Gtk.Button();
		this.createButton.CanFocus = true;
		this.createButton.Name = "createButton";
		this.createButton.UseUnderline = true;
		this.createButton.Label = global::Mono.Unix.Catalog.GetString("Create");
		this.processButtons.Add(this.createButton);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.processButtons[this.createButton]));
		w3.Expand = false;
		w3.Fill = false;
		// Container child processButtons.Gtk.ButtonBox+ButtonBoxChild
		this.readButton = new global::Gtk.Button();
		this.readButton.CanFocus = true;
		this.readButton.Name = "readButton";
		this.readButton.Label = global::Mono.Unix.Catalog.GetString("Read");
		this.processButtons.Add(this.readButton);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.processButtons[this.readButton]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child processButtons.Gtk.ButtonBox+ButtonBoxChild
		this.updateButton = new global::Gtk.Button();
		this.updateButton.CanFocus = true;
		this.updateButton.Name = "updateButton";
		this.updateButton.UseUnderline = true;
		this.updateButton.Label = global::Mono.Unix.Catalog.GetString("Update");
		this.processButtons.Add(this.updateButton);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.processButtons[this.updateButton]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child processButtons.Gtk.ButtonBox+ButtonBoxChild
		this.deleteButton = new global::Gtk.Button();
		this.deleteButton.CanFocus = true;
		this.deleteButton.Name = "deleteButton";
		this.deleteButton.UseUnderline = true;
		this.deleteButton.Label = global::Mono.Unix.Catalog.GetString("Delete");
		this.processButtons.Add(this.deleteButton);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.processButtons[this.deleteButton]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.contactsDBLayout.Add(this.processButtons);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.contactsDBLayout[this.processButtons]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		w7.Padding = ((uint)(4));
		this.Add(this.contactsDBLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 723;
		this.DefaultHeight = 564;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.contactsDBTreeView.CursorChanged += new global::System.EventHandler(this.OnContactsDBTreeViewCursorChanged);
		this.createButton.Clicked += new global::System.EventHandler(this.OnCreateButtonClicked);
		this.readButton.Clicked += new global::System.EventHandler(this.OnReadButtonClicked);
		this.updateButton.Clicked += new global::System.EventHandler(this.OnUpdateButtonClicked);
		this.deleteButton.Clicked += new global::System.EventHandler(this.OnDeleteButtonClicked);
	}
}
